In [5]:
import tensorflow as tf

# Set random seed for reproducibility
tf.random.set_seed(42)

# Create a random tensor of shape (4, 6)
tensor = tf.random.uniform(shape=(4, 6))
print("Original Tensor:\n", tensor.numpy())
# Get the rank and shape of the tensor
rank = tf.rank(tensor)
shape = tf.shape(tensor)

print("Rank of the tensor:", rank.numpy())
print("Shape of the tensor:", shape.numpy())
# Reshape the tensor to (2, 3, 4)
reshaped_tensor = tf.reshape(tensor, (2, 3, 4))
print("Reshaped Tensor (2, 3, 4):\n", reshaped_tensor.numpy())

# Transpose the reshaped tensor to (3, 2, 4)
transposed_tensor = tf.transpose(reshaped_tensor, perm=[1, 0, 2])
print("Transposed Tensor (3, 2, 4):\n", transposed_tensor.numpy())
# Create a smaller tensor of shape (1, 4)
smaller_tensor = tf.constant([[1.0, 2.0, 3.0, 4.0]])

# Broadcast the smaller tensor to match the shape of the larger tensor (3, 2, 4)
broadcasted_tensor = tf.broadcast_to(smaller_tensor, transposed_tensor.shape)
print("Broadcasted Tensor:\n", broadcasted_tensor.numpy())

# Add the broadcasted tensor to the transposed tensor
result_tensor = transposed_tensor + broadcasted_tensor
print("Result Tensor after Addition:\n", result_tensor.numpy())

Original Tensor:
 [[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236]
 [0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358 ]
 [0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307 ]
 [0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061 ]]
Rank of the tensor: 2
Shape of the tensor: [4 6]
Reshaped Tensor (2, 3, 4):
 [[[0.6645621  0.44100678 0.3528825  0.46448255]
  [0.03366041 0.68467236 0.74011743 0.8724445 ]
  [0.22632635 0.22319686 0.3103881  0.7223358 ]]

 [[0.13318717 0.5480639  0.5746088  0.8996835 ]
  [0.00946367 0.5212307  0.6345445  0.1993283 ]
  [0.72942245 0.54583454 0.10756552 0.6767061 ]]]
Transposed Tensor (3, 2, 4):
 [[[0.6645621  0.44100678 0.3528825  0.46448255]
  [0.13318717 0.5480639  0.5746088  0.8996835 ]]

 [[0.03366041 0.68467236 0.74011743 0.8724445 ]
  [0.00946367 0.5212307  0.6345445  0.1993283 ]]

 [[0.22632635 0.22319686 0.3103881  0.7223358 ]
  [0.72942245 0.54583454 0.10756552 0.6767061 ]]]
Broadcasted 